import dataclasses
import os
from typing import Literal, Any

import streamlit.components.v1 as components
import streamlit as st

parent_dir = os.path.dirname(os.path.abspath(__file__))
build_dir = os.path.join(parent_dir, "source")


@dataclasses.dataclass
class TokenReplayPreferences:
    # If true, :DF_C edges that are participating in any of the token flows will be highlighted
    animate_active_elements_flag: bool

    # If true, token replay will enable
    animate_tokens_flag: bool

    # How fast are tokens moving
    token_animation_speed: float

    # At-once: All tokens start at the same time
    # Real-time: Tokens are added to the replay with time offset proportional to the
    # delta between its first event and first event in the sample.
    token_animation_alignment: Literal["At-once", "Real-time"]

    # If true, the animation will take the same amount of time for all tokes no matter how long
    # the case was executing
    # If false, the token replay duration will be scaled according to case duration
    fixed_animation_duration: bool


@dataclasses.dataclass
class ReplayMetadata:
    start_date: str
    end_date: str
    total_duration_sec: float


@dataclasses.dataclass
class ReplaySegment:
    dfc_element_id: str
    color: str
    start_offset_sec: float
    duration_sec: float
    activity_duration_sec: float


@dataclasses.dataclass
class Token:
    element_id: Any
    entity_id: Any
    entity_type: str
    segments: list[ReplaySegment]
    replay_duration_sec: float


@dataclasses.dataclass
class GraphFrontendPayload:
    # Dot source code generated by ObjektViz backend
    dot_source: str

    # elementIds of all active/selected :Class and :DF_C elements, this might be used, for instance in combination
    # with animate_active_elements_flag
    active_element_ids: list

    # If true, dashed animation will be played when hovering over :DF_C
    enable_path_effects_on_hover: bool

    animation_preferences: TokenReplayPreferences

    # Process trances for token replay
    # List of these dicts:
    #   element_id (str): Unique identifier of the process element.
    #   entity_id (str): Identifier of the entity associated with the trace.
    #   color (str): Token color in HEX format.
    #   start_offset (int): Time delta (in minutes) between the first event of the trace
    #                       and the first event in the sample.
    #   segments (List[Dict[...]]): A list of segment dictionaries, where each segment
    #             represents an instance trace with additional metadata. Each segment contains:
    #             - ProcletEdgeElementId (str): Identifier of the edge element.
    #             - StartClass (str): Name of the starting class.
    #             - EndClass (str): Name of the ending class.
    #             - StartTime (str): timestamp of the start event.
    #             - EndTime (str): timestamp of the end event.
    #             - TransitionDurationInMinutes (int): Duration of the transition in minutes.
    tokens: list[Token]

    # TODO
    replay_metadata: ReplayMetadata | None

    # Precomputed relations between different graph elements (usefully for e.g. brushing to find all related items to
    # selection)
    edge_node_map: dict[str, list[str]]  # {"Edge ID": [list of connected nodes]}
    node_edge_map: dict[str, list[str]]  # {"Node ID": [list of connected edges]}
    node_node_map: dict[
        str, list[str]
    ]  # {"Node ID": [list of connected nodes (transitive over edges)]}

    # Element id of element that was selected by clicking on it
    # (ui click)->(streamlit event)->(st.session is set)->(this property is set)->(ui receives new payload)->(ui updated)
    selected_element_id: str

    # Precision in percents for graph  morphing animation
    # morphing_precision: int = 20


_proclet_graph = components.declare_component(name="proclet_vis", path=build_dir)


def interactive_proclet_graph(payload: GraphFrontendPayload):
    """ObjektViz frontend"""
    return _proclet_graph(key="proclet_graph", **dataclasses.asdict(payload))


def wire_graph_event(graph_event):
    """Consume ObjektViz frontend callback and update the session accordingly"""
    if graph_event is None:
        return

    if graph_event['eventType'] == 'RightClick' and graph_event["elementId"] not in st.session_state["excluded_elements"]:
        st.session_state['excluded_elements'].add(graph_event["elementId"])
        st.rerun()

    if graph_event['eventType'] == 'LeftClick' and graph_event["elementId"] not in [
        st.session_state.get("selected_node"),
        st.session_state.get("selected_edge"),
        st.session_state.get("selected_token"),
    ]:
        st.session_state.selected_node = None
        st.session_state.selected_edge = None
        st.session_state.selected_token = None

        if (
            graph_event["type"] == "edge"
            and graph_event["elementId"] != st.session_state.selected_edge
        ):
            st.session_state.selected_edge = graph_event["elementId"]
        elif (
            graph_event["type"] == "node"
            and graph_event["elementId"] != st.session_state.selected_node
        ):
            st.session_state.selected_node = graph_event["elementId"]
        elif graph_event["type"] == "token-group":
            st.session_state.selected_token = graph_event["elementId"]

        st.rerun()
