name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Install publish dependencies
        run: uv sync --extra publish

      - name: Build
        run: uv run python -m build

      - name: Publish
        run: uv run twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
